### ISSUE TITLE
ConnectionShutdown is not implemented at FakeConnection on nuget package.

### ISSUE THREAD

**Issue by forlayo** [Parametric/RabbitMQ.Fakes#12]
I am using the NuGet package for NetCore and for NetStandard and I am getting an issue as apparently FakeConnection does not implement ConnectionShutdown event :/

```
Test Name:	Send_message
Test FullName:	SpotMessage.Tests.RabbitServiceTest.Send_message
Test Source:	C:\workspace\SpotWorld\SpotMessage.Tests\RabbitServiceTest.cs : line 78
Test Outcome:	Failed
Test Duration:	0:00:00.0296631

Result StackTrace:	
at RabbitMQ.Fakes.FakeConnection.RabbitMQ.Client.IConnection.add_ConnectionShutdown(EventHandler`1 value)
   at SpotMessage.RabbitService.Init(String uuid, Boolean clientRole) in C:\workspace\SpotWorld\SpotMessage\RabbitService.cs:line 72
   at SpotMessage.RabbitService.InitAsClient(String uuid) in C:\workspace\SpotWorld\SpotMessage\RabbitService.cs:line 58
   at SpotMessage.Tests.RabbitServiceTest.Send_message() in C:\workspace\SpotWorld\SpotMessage.Tests\RabbitServiceTest.cs:line 91
Result Message:	
Test method SpotMessage.Tests.RabbitServiceTest.Send_message threw exception: 
System.NotImplementedException: The method or operation is not implemented.
```

**Comment by serpentfabric** [comment]
@forlayo the latest code in master seems to support this now. are you using a forked project like rabbitmq.fakes.dotnetcore?

**Comment by Bill-Manning** [comment]
It looks like we don't have a maintainer for this project anymore. I think you should consider it a dead project and find an alternate. 👍
